# fly.toml app configuration file generated for utility-splitter on 2024-03-20

app = "utility-splitter"
primary_region = "sin" # Singapore, change as needed

[build]
  dockerfile = "Dockerfile.fly"

[env]
  PORT = "3000"

[mounts]
  source = "utility_data"
  destination = "/app/server/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
